In [1]:
import numpy as np
import pandas as pd

In [5]:
eco_data = pd.read_excel("./eco.xls", sheet_name='All persons')
crime_data = pd.read_excel("./crime.xlsx", sheet_name='Crime Rates')

In [9]:
eco_code = eco_data['Unnamed: 0']
crime_code =

In [10]:
print(crime_data)

   Unnamed: 0              Unnamed: 1 All recorded offences Unnamed: 3  \
0        Code                 Borough               1999-00    2000-01
1         NaN                     NaN                   NaN        NaN
2   E09000002    Barking and Dagenham               120.454    123.575
3   E09000003                  Barnet               97.9618    95.6762
4   E09000004                  Bexley               95.0988    96.3437
5   E09000005                   Brent                127.74    122.716
6   E09000006                 Bromley               89.7722    88.5218
7   E09000007                  Camden               241.049    238.452
8   E09000008                 Croydon               113.661    105.376
9   E09000009                  Ealing               128.161    126.727
10  E09000010                 Enfield               104.821    101.862
11  E09000011               Greenwich               141.355    131.343
12  E09000012                 Hackney               195.929    188.031
13  E09000013  Hammersmith and Fulham               178.044    171.759
14  E09000014                Haringey               155.908    149.191
15  E09000015                  Harrow                80.694    81.4436
16  E09000016                Havering               83.2344    87.7717
17  E09000017              Hillingdon               107.246    108.734
18  E09000018                Hounslow               144.808    135.211
19  E09000019               Islington               218.687    202.236
20  E09000020  Kensington and Chelsea                208.42    198.589
21  E09000021    Kingston upon Thames               100.334    96.8248
22  E09000022                 Lambeth               195.685    188.684
23  E09000023                Lewisham               118.365    110.327
24  E09000024                  Merton               90.8452    88.0412
25  E09000025                  Newham               159.386    157.971
26  E09000026               Redbridge               103.209    105.166
27  E09000027    Richmond upon Thames               89.7316    84.9121
28  E09000028               Southwark               176.451    160.043
29  E09000029                  Sutton               80.7972    77.2253
30  E09000030           Tower Hamlets               176.071      177.9
31  E09000031          Waltham Forest               122.299    116.455
32  E09000032              Wandsworth                134.46    129.834
33  E09000033             Westminster               463.001    424.368
34        NaN                Heathrow                   NaN        NaN
35  E13000001            Inner London               195.516    186.787
36  E13000002            Outer London               107.124    104.515
37        NaN                     NaN                   NaN        NaN
38  E12000007         Met Police Area                142.05    137.387
39        NaN                     NaN                   NaN        NaN
40        727       England and Wales                   NaN        NaN

   Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
0     2001-02    2002-03    2003-04    2004-05    2005-06    2006-07  ...
1         NaN        NaN        NaN        NaN        NaN        NaN  ...
2     123.981    122.592    133.229    129.473    132.684    127.928  ...
3      101.02    107.121    112.765    117.035    106.463    90.4471  ...
4     96.9112    90.1412     92.466    85.3669    89.9812    76.1241  ...
5     123.418     124.27    133.559    132.603    129.697    110.212  ...
6     96.6788    102.053    104.012    103.465    102.842    94.4435  ...
7      262.15    264.203    249.767    219.117    200.087    201.083  ...
8     111.754    115.135    110.274    103.828    102.813    92.5542  ...
9     127.338    129.824    123.096     117.45    119.239    116.494  ...
10    106.039    107.008    106.438    99.6786    96.4713     94.138  ...
11    133.335    140.882    139.753    137.268     136.03     127.48  ...
12    191.893    186.134    183.776    170.858    159.945    141.512  ...
13    174.094    174.447    167.046    157.709    149.234    145.035  ...
14    170.218    173.815    163.567    156.986    154.258    131.211  ...
15    86.7294    92.1794    86.2311    83.7252    79.0606    70.8172  ...
16    97.3135     95.697    98.4026    94.9245    95.9161      87.63  ...
17    118.372    118.245    118.317    111.785    112.862    110.635  ...
18    138.576    151.424    140.491    127.178    121.698    107.331  ...
19    209.664    218.884    225.629    209.898    201.933    190.239  ...
20    182.523    194.846    180.755     161.76     146.88    147.224  ...
21    92.6633    95.7619    108.957    103.869    99.2924    85.2818  ...
22    208.844    198.461     183.46    166.935    151.171    138.555  ...
23    114.054    113.391    125.337    137.977    130.965    124.624  ...
24    92.8647    93.8282    98.9868    91.4784    90.7689    83.5134  ...
25    162.848    161.222    158.514    143.298    153.744    137.976  ...
26    115.758    117.643    114.942    105.208    98.1038    96.4279  ...
27     92.117    95.8385    87.1759    85.4377    82.0405    73.4604  ...
28    178.048    179.343    181.302    170.145    158.252     148.43  ...
29    84.6408    82.6801    89.1172    93.5536    88.2852     84.251  ...
30    185.355    198.637    187.816     172.05    158.195    149.391  ...
31    136.297     144.18    137.929     131.07    132.937    125.371  ...
32    131.437    131.691    121.256    113.565     106.38     104.47  ...
33    424.288    413.988    375.794    369.776    320.806    297.389  ...
34        NaN        NaN        NaN        NaN        NaN        NaN  ...
35    195.469    196.155    188.594    177.488    166.095    155.322  ...
36    110.065     112.91    113.028    108.796    106.742    98.1662  ...
37        NaN        NaN        NaN        NaN        NaN        NaN  ...
38    144.401    146.508    143.469    136.574    130.885    121.321  ...
39        NaN        NaN        NaN        NaN        NaN        NaN  ...
40        NaN    112.152    112.263    104.656    102.288    99.1989  ...

   Unnamed: 190 Unnamed: 191 Unnamed: 192 Unnamed: 193 Unnamed: 194  \
0        2007.0       2008.0       2009.0       2010.0       2011.0
1           NaN          NaN          NaN          NaN          NaN
2      169031.0     172452.0     177580.0     182838.0     187029.0
3      334837.0     339212.0     345829.0     351438.0     357538.0
4      224625.0     226652.0     228146.0     230711.0     232774.0
5      283273.0     290901.0     298118.0     304785.0     312245.0
6      302625.0     304968.0     306924.0     308560.0     310554.0
7      211520.0     210273.0     212924.0     214725.0     220087.0
8      344029.0     349308.0     352763.0     357951.0     364815.0
9      318671.0     324022.0     329966.0     334073.0     339314.0
10     291534.0     297443.0     301971.0     307648.0     313935.0
11     236535.0     239748.0     243672.0     249171.0     255483.0
12     224480.0     231041.0     236622.0     241739.0     247182.0
13     176472.0     177088.0     180116.0     180842.0     182445.0
14     236793.0     244459.0     249805.0     252742.0     255540.0
15     226355.0     229567.0     233495.0     237451.0     240499.0
16     229789.0     231793.0     234127.0     236234.0     237927.0
17     256981.0     261051.0     265665.0     269465.0     275499.0
18     233454.0     237907.0     243366.0     249236.0     254927.0
19     188636.0     192089.0     196704.0     200129.0     206285.0
20     162883.0     162579.0     161893.0     160463.0     158251.0
21     154485.0     156027.0     157307.0     158648.0     160436.0
22     284964.0     289126.0     294050.0     297650.0     304481.0
23     261188.0     266508.0     270418.0     272525.0     276938.0
24     194260.0     195859.0     198136.0     199136.0     200543.0
25     266285.0     276478.0     286447.0     299171.0     310460.0
26     259965.0     265452.0     270435.0     275088.0     281395.0
27     182421.0     182927.0     184394.0     186304.0     187527.0
28     272626.0     276973.0     281120.0     283777.0     288717.0
29     184174.0     185860.0     188167.0     189321.0     191123.0
30     225251.0     231893.0     240495.0     248520.0     256012.0
31     235665.0     242098.0     248140.0     254009.0     259742.0
32     291440.0     294305.0     299347.0     302620.0     307710.0
33     220619.0     218673.0     216980.0     217187.0     219582.0
34          NaN          NaN          NaN          NaN          NaN
35    3030764.0    3078914.0    3134393.0    3179428.0    3241102.0
36    4662709.0    4733247.0    4808201.0    4882067.0    4963305.0
37          NaN          NaN          NaN          NaN          NaN
38    7693473.0    7812161.0    7942594.0    8061495.0    8204407.0
39          NaN          NaN          NaN          NaN          NaN
40   54387392.0   54841720.0   55235253.0   55692423.0   56170927.0

   Unnamed: 195 Unnamed: 196 Unnamed: 197 Unnamed: 198 Unnamed: 199
0        2012.0       2013.0       2014.0       2015.0       2016.0
1           NaN          NaN          NaN          NaN          NaN
2      190560.0     194352.0     198294.0     201979.0     206460.0
3      363956.0     369088.0     374915.0     379691.0     386083.0
4      234271.0     236687.0     239865.0     242142.0     244760.0
5      314660.0     317264.0     320762.0     324012.0     328254.0
6      314036.0     317899.0     321278.0     324857.0     326889.0
7      224962.0     229719.0     234846.0     241059.0     246181.0
8      368886.0     372752.0     376040.0     379031.0     382304.0
9      340671.0     342494.0     342118.0     343059.0     343196.0
10     317287.0     320524.0     324574.0     328433.0     331395.0
11     260068.0     264008.0     268678.0     274803.0     279766.0
12     252119.0     257379.0     263150.0     269009.0     273526.0
13     179850.0     178685.0     178365.0     179410.0     179654.0
14     258912.0     263386.0     267541.0     272864.0     278451.0
15     242377.0     243372.0     246011.0     247130.0     248752.0
16     239733.0     242080.0     245974.0     249085.0     252783.0
17     281756.0     286806.0     292690.0     297735.0     302471.0
18     259052.0     262407.0     265568.0     268770.0     271139.0
19     211047.0     215667.0     221030.0     227692.0     232865.0
20     155930.0     155594.0     156190.0     157711.0     156726.0
21     163906.0     166793.0     169958.0     173525.0     176107.0
22     310200.0     314242.0     318216.0     324431.0     327910.0
23     281556.0     286180.0     291933.0     297325.0     301867.0
24     202225.0     203223.0     203515.0     204565.0     205029.0
25     314084.0     318227.0     324322.0     332817.0     340978.0
26     284617.0     288272.0     293055.0     296793.0     299249.0
27     189145.0     191365.0     193585.0     194730.0     195846.0
28     293530.0     298464.0     302538.0     308901.0     313223.0
29     193630.0     195914.0     198134.0     200145.0     202220.0
30     263003.0     272890.0     284015.0     295236.0     304854.0
31     262566.0     265797.0     268020.0     271170.0     275843.0
32     308312.0     310516.0     312145.0     314544.0     316096.0
33     223858.0     226841.0     233292.0     242299.0     247614.0
34          NaN          NaN          NaN          NaN          NaN
35    3284967.0    3335438.0    3395655.0    3472058.0    3529346.0
36    5023402.0    5081097.0    5143034.0    5201655.0    5258546.0
37          NaN          NaN          NaN          NaN          NaN
38    8308369.0    8416535.0    8538689.0    8673713.0    8787892.0
39          NaN          NaN          NaN          NaN          NaN
40   56567796.0   56948229.0   57408654.0   57885413.0   58381217.0

[41 rows x 200 columns]

In [38]:
data_crime['Code'][0:40]

0     E09000002
1     E09000003
2     E09000004
3     E09000005
4     E09000006
5     E09000007
6     E09000008
7     E09000009
8     E09000010
9     E09000011
10    E09000012
11    E09000013
12    E09000014
13    E09000015
14    E09000016
15    E09000017
16    E09000018
17    E09000019
18    E09000020
19    E09000021
20    E09000022
21    E09000023
22    E09000024
23    E09000025
24    E09000026
25    E09000027
26    E09000028
27    E09000029
28    E09000030
29    E09000031
30    E09000032
31    E09000033
32          NaN
33    E13000001
34    E13000002
35    E12000007
36          727
37    E09000002
38    E09000003
39    E09000004
Name: Code, dtype: object